server:
  port: 9001
  servlet:
    context-path: /service-mybatis
  tomcat:
    max-threads: 1000
    max-connections: 20000
    max-http-post-size: 10
    max-http-header-size: 20
    max-swallow-size: 30
# 注册到注册中心
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7777/eureka/
spring:
  http:
    encoding:
      charset: utf-8
  jackson:
    default-property-inclusion: non_null
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${JDBC_URL:jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      max-lifetime: 28500
      maximum-pool-size: 20
      idle-timeout: 6000000
      connection-test-query: "SELECT 1"
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true
  #redis
  redis:
    #redis机器ip
    hostname: 127.0.0.1
    #redis端口
    port: 6379
    #redis密码
    password: root
    #redis超时时间（毫秒），如果不设置，取默认值2000
    timeout: 1000
    #最大空闲数
    maxIdle: 300
    #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
    #maxActive=600
    #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    maxTotal: 1000
    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    maxWaitMillis: 1000
    #连接的最小空闲时间 默认1800000毫秒(30分钟)
    minEvictableIdleTimeMillis: 300000
    #每次释放连接的最大数目,默认3
    numTestsPerEvictionRun: 1024
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    timeBetweenEvictionRunsMillis: 30000
    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    #在空闲时检查有效性, 默认false
    testWhileIdle: true
logging:
  path: ${LOG_PATH:./log/}
  level:
    root: ${LOG_LEVEL:info}
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.biz.primus.ms.activity.dao.mapper
  configuration:
    map-underscore-to-camel-case: true

    # 控制台打印sql语句,调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  security:
    enabled: false
primus:
  short:
    message:
      config:
        enabled: true
        accessKeyId: LTAIujgfrvwRjhbX
        accessKeySecret: ldSZZyuvDEX4CW47bWqQBMEen582Ph
  redis:
    maxTotal: 120
    maxIdle: 10
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 30000
    testOnBorrow: true
    host: 127.0.0.1
    port: 6379
    name:
    password: root
  zookeeper:
    url: 127.0.0.1:2181