primus:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password: root
  zookeeper:
    url: 127.0.0.1:2181
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/monitor?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root